

# DataSource Config
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: 02191219hh
    url: jdbc:mysql://127.0.0.1:3306/clever-ai?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

