

# DataSource Config
spring:
  profiles:
    active: @profiles.active@

server:
  port: 9992
  context-path: /clever-ai


chatgpt:
  token: RKvAEDLAoh98+xsqgwZpE0d9M6rcJRwKUeuWqrTFIzi9LTHE1ZLMh8s2lVzvpb4Pnwx1NyaYdZlIgLs7OT94Hg==
  proxy-host: 127.0.0.1
  proxy-port: 7890
  model: text-davinci-003 #可选
  chat-model: gpt-3.5-turbo #可选
  retries: 10 #可选，默认为5
  session-expiration-time: 30 #可选，不填则会话永不过期
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml